stages:
  # -----------------------------------------------------------------
  # Task 0: Exploratory Analysis (Independent)
  # -----------------------------------------------------------------
  analyze_completeness:
    cmd: julia --project=. task0_completeness.jl
    deps:
      - "../data/arrow/"
      - task0_completeness.jl
    # These are not cached "outputs" but reports to track changes over time
    metrics:
      - metrics/completeness.json

  # -----------------------------------------------------------------
  # Task A0: Ingestion & ID Assignment
  # -----------------------------------------------------------------
  ingest_catalog:
    cmd: julia --project=. taskA0_ingest.jl
    deps:
      - "../data/arrow/"
      - taskA0_ingest.jl
    outs:
      - data/catalog_all.arrow

  # -----------------------------------------------------------------
  # Task A: Binning / Partitioning
  # -----------------------------------------------------------------
  partition_catalog:
    # The script reads params.yaml to determine how to split the Arrow file
    cmd: julia --project=. taskA_partition.jl
    deps:
      - data/catalog_all.arrow
      - taskA_partition.jl
    params:
      - params.yaml:
          - Mc # If Mc changes, we must re-bin
          - criteria # If definitions (slices) change, we must re-bin
          - K_means
    outs:
      - data/binned:
          cache: true
          # DVC tracks the directory state (Hive-style: criterion=<tag>/partition=<n>/data.arrow)

  # -----------------------------------------------------------------
  # Task B: K-Means Clustering
  # -----------------------------------------------------------------
  cluster_events:
    # Iterates over all arrow files found in data/binned/
    cmd: julia --project=. taskB_cluster.jl
    deps:
      - data/binned
      - taskB_cluster.jl
    params:
      - params.yaml:
          - K_means
    outs:
      # criterion=<tag>/partition=<n>/k=<k>/data.arrow
      - data/cluster_assignments
      - data/centroid_coordinates

  # -----------------------------------------------------------------
  # Task C: Voronoi Boundaries
  # -----------------------------------------------------------------
  generate_taiwan_coastline:
    # Load the shape file and extract coastline.
    cmd: julia --project=. taiwan_coastline.jl
    deps:
      - ../data/map/Taiwan
    outs:
      - assets/taiwan_coastline.geojson
  generate_boundaries:
    # Uses centroids to draw polygons and clips them to the coastline
    cmd: julia --project=. taskC_boundaries.jl
    deps:
      - data/centroid_coordinates
      - assets/taiwan_coastline.geojson
      - taskC_boundaries.jl
    outs:
      # criterion=<tag>/partition=<n>/k=<k>/data.arrow
      - data/voronoi_boundaries
