# Global Physics Parameters
# Magnitude of completeness $M_c$
Mc:
  cutoff:
    - 2.0 # Determined by Task 0

K_means:
  k:
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20 # Number of clusters for this strategy

# Binning Strategies
criteria:
  # Strategy 1: Standard depth slicing
  depth_iso:
    func: "bin_by_depth_edges"
    args: # The edges of the bins
      edges: [0, 10, 30, 300]

  # Strategy 2: Deep vs Shallow (Simple boolean split)
  crustal_split:
    func: "bin_by_boolean_filter"
    args:
      cutoff: [5.0, 10.0, 15.0, 20.0, 25.0, 30.0]
